### ISSUE TITLE
Strategies constructor Declaration is different than the parent error

### ISSUE THREAD

**Issue by minamassoud** [ajcastro/scribe-tdd#11]
using the latest versions of both scribe-tdd and scribe.
example: 
`public function __invoke(ExtractedEndpointData $endpointData, array $routeRules): ?array`

should be:
`public function __invoke(ExtractedEndpointData $endpointData, array $routeRules = []): ?array`

**Comment by ajcastro** [comment]
Hi @Mina-R-Meshriky pls send PR thank you! 😊

**Comment by joelvh** [comment]
@Mina-R-Meshriky @ajcastro i've fixed these in #12

**Comment by ajcastro** [comment]
Closing this issue, thanks guys!
