### ISSUE TITLE
Undefined array key "test_class" in $testResult

### ISSUE THREAD

**Issue by rarg27** [ajcastro/scribe-tdd#9]
Encountered this issue in my first time use. Did I miss something?

![error](https://user-images.githubusercontent.com/20268510/157815003-4a56d748-b9b9-474b-95c0-eb3bd2bd4598.PNG)

I think the `$testResult` variable does not contain the extra properties set in ExampleCreator instance since these properties aren't written among other files in `./scribe-tdd`.

Do you want a PR fix?

**Comment by ajcastro** [comment]
@rarg27 PRs are welcome. Thanks!

**Comment by ajcastro** [comment]
Closing this issue. Thanks guys!
